"""Session 9 homework: compare RAG answers against bare foundation model answers.

Run from backend/ after ingest_knowledge.py has loaded the documents:

    ..\\.venv\\Scripts\\python.exe compare_rag_vs_base.py

Each question in knowledge/evaluation-questions.json is asked twice. Once through
retrieval, once through the model alone. The result is written to
evidence/session-09-rag-vs-base.md.

The scoring is deliberately mechanical. Every expected fact in the questions file
carries its own list of accepted strings, and a fact counts as stated when any of
them appears in the answer. The alternatives live in the JSON rather than in this
script, so anyone can audit what was accepted and what was not.
"""

import hashlib
import json
import os
import re
from datetime import datetime, timezone
from pathlib import Path

from database import SessionLocal
from models.knowledge import KnowledgeChunk  # noqa: F401 - registers the table in metadata
from services.knowledge_service import (
    KnowledgeBaseError,
    answer_without_knowledge_base,
    ask_knowledge_base,
)

REPO_ROOT = Path(__file__).resolve().parents[1]
QUESTIONS_FILE = REPO_ROOT / "knowledge" / "evaluation-questions.json"
OUTPUT_FILE = REPO_ROOT / "evidence" / "session-09-rag-vs-base.md"


def _normalise(text: str) -> str:
    """Lowercase and collapse whitespace, so line breaks never decide a match."""

    return re.sub(r"\s+", " ", text.lower())


def count_facts_present(answer: str, expected_facts: list[dict]) -> tuple[int, list[str]]:
    """Return how many expected facts appear in an answer, and which ones are missing."""

    haystack = _normalise(answer)
    present = 0
    missing: list[str] = []

    for fact in expected_facts:
        if any(_normalise(candidate) in haystack for candidate in fact["match"]):
            present += 1
        else:
            missing.append(fact["fact"])

    return present, missing


def _source_matches(sources: list[dict], required_document: str) -> bool:
    """Return whether retrieval cited the document the frozen case requires."""

    return any(source.get("document") == required_document for source in sources)


def _clean_code_block(text: str) -> str:
    """Keep model line breaks while removing trailing whitespace."""

    return "\n".join(line.rstrip() for line in text.strip().splitlines())


def _render(
    results: list[dict],
    mode: str,
    dataset_hash: str,
    revision: str,
) -> str:
    """Build the evidence document."""

    stamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    rag_total = sum(item["rag_present"] for item in results)
    base_total = sum(item["base_present"] for item in results)
    fact_total = sum(item["fact_count"] for item in results)
    cited = sum(1 for item in results if item["sources"])
    correct_source = sum(1 for item in results if item["required_source_hit"])
    complete = sum(
        1
        for item in results
        if item["rag_present"] == item["fact_count"] and item["required_source_hit"]
    )

    if complete == len(results) and rag_total > base_total:
        verdict = "PASS"
    elif rag_total > base_total:
        verdict = "CONDITIONAL"
    else:
        verdict = "FAIL"

    lines = [
        "# Session 09 Evidence - RAG versus Base Model",
        "",
        "Generated by `backend/compare_rag_vs_base.py`. Do not edit by hand.",
        "",
        f"Run at {stamp}. Retrieval mode `{mode}`.",
        "",
        "## So What?",
        "",
        f"**Verdict: {verdict}.** The same five Bangladesh questions were asked",
        "twice: once with retrieval and once through the same foundation model",
        "without documents. The test measures document-grounded specificity, not",
        "general travel intelligence or current real-world travel conditions.",
        "",
        "## Reproduction metadata",
        "",
        f"- Dataset revision: `{revision}`",
        f"- Dataset SHA-256: `{dataset_hash}`",
        f"- Foundation model: `{os.getenv('MODEL_ID', 'not-set')}`",
        f"- AWS region: `{os.getenv('AWS_REGION', 'not-set')}`",
        "- Answer settings: temperature `0.0`, maximum `500` tokens",
        f"- Retrieval mode: `{mode}`",
        "",
        "## Scoreboard",
        "",
        "| Path | Expected facts stated | Any source | Required source | Complete cases |",
        "|---|---:|---:|---:|---:|",
        f"| RAG | {rag_total} of {fact_total} | {cited} of {len(results)} | {correct_source} of {len(results)} | {complete} of {len(results)} |",
        f"| Base model | {base_total} of {fact_total} | 0 of {len(results)} | 0 of {len(results)} | Not applicable |",
        "",
        "A fact counts as stated when one of its accepted strings, listed in",
        "`knowledge/evaluation-questions.json`, appears in the answer. No partial",
        "credit and no human judgement at scoring time.",
        "",
        "## Question by question",
        "",
    ]

    for item in results:
        lines += [
            f"### {item['id']}. {item['question']}",
            "",
            f"Case `{item['case_id']}` - split `{item['split']}` - severity `{item['severity']}`.",
            "",
            f"Requires `{item['requires_document']}`. {item['why_base_model_fails']}",
            "",
            "**Expected facts**",
            "",
        ]
        lines += ["- " + fact["fact"] for fact in item["expected_facts"]]
        lines += [
            "",
            f"**RAG answer** ({item['rag_present']} of {item['fact_count']} facts stated)",
            "",
            "```text",
            _clean_code_block(item["rag_answer"]),
            "```",
            "",
            "**Sources retrieved**",
            "",
        ]

        if item["sources"]:
            lines += ["| Document | Score | Required document? |", "|---|---:|---|"]
            lines += [
                "| `"
                + source["document"]
                + "` | "
                + str(source["score"])
                + " | "
                + ("Yes" if source["document"] == item["requires_document"] else "No")
                + " |"
                for source in item["sources"]
            ]
        else:
            lines.append("None. Nothing scored above the retrieval floor.")

        lines += [
            "",
            f"**Base model answer** ({item['base_present']} of {item['fact_count']} facts stated)",
            "",
            "```text",
            _clean_code_block(item["base_answer"]),
            "```",
            "",
            f"**Measured delta:** RAG stated {item['rag_present'] - item['base_present']:+d} more expected fact(s). Required source retrieved: {'yes' if item['required_source_hit'] else 'no'}.",
            "",
        ]

        if item["rag_missing"]:
            lines += ["Facts the RAG answer did not state:", ""]
            lines += ["- " + fact for fact in item["rag_missing"]]
            lines.append("")

        lines.append("---")
        lines.append("")

    lines += [
        "## How to read this",
        "",
        "The base model can occasionally state a true Bangladesh fact from training",
        "data. That still does not prove it used the assigned document. RAG earns",
        "grounding credit only when the expected facts and the required source file",
        "are both present.",
        "",
        "This is a five-case convenience sample with deterministic string matching.",
        "It is sufficient for the homework comparison, not a production reliability",
        "claim. Timings, permissions, closures, and safety advice must be refreshed",
        "from current authorities before being used for an actual trip.",
    ]

    return "\n".join(lines) + "\n"


def compare() -> None:
    """Ask every evaluation question twice and write the evidence document."""

    payload = json.loads(QUESTIONS_FILE.read_text(encoding="utf-8"))
    questions = payload["questions"]
    dataset_hash = hashlib.sha256(QUESTIONS_FILE.read_bytes()).hexdigest()

    db = SessionLocal()
    results: list[dict] = []
    mode = "unknown"

    try:
        for item in questions:
            question = item["question"]
            print(f"{item['id']} ...", flush=True)

            grounded = ask_knowledge_base(db, question)
            mode = grounded["mode"]
            base_answer = answer_without_knowledge_base(question)

            rag_present, rag_missing = count_facts_present(
                grounded["answer"], item["expected_facts"]
            )
            base_present, base_missing = count_facts_present(
                base_answer, item["expected_facts"]
            )
            required_source_hit = _source_matches(
                grounded["sources"], item["requires_document"]
            )

            results.append(
                {
                    "id": item["id"],
                    "case_id": item["case_id"],
                    "split": item["split"],
                    "severity": item["severity"],
                    "question": question,
                    "requires_document": item["requires_document"],
                    "why_base_model_fails": item["why_base_model_fails"],
                    "expected_facts": item["expected_facts"],
                    "fact_count": len(item["expected_facts"]),
                    "rag_answer": grounded["answer"],
                    "sources": grounded["sources"],
                    "rag_present": rag_present,
                    "rag_missing": rag_missing,
                    "base_answer": base_answer,
                    "base_present": base_present,
                    "base_missing": base_missing,
                    "required_source_hit": required_source_hit,
                }
            )
    except KnowledgeBaseError as error:
        raise RuntimeError(f"Comparison stopped, Bedrock refused a call: {error}") from error
    finally:
        db.close()

    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_FILE.write_text(
        _render(results, mode, dataset_hash, payload["revision"]), encoding="utf-8"
    )

    rag_total = sum(item["rag_present"] for item in results)
    base_total = sum(item["base_present"] for item in results)
    fact_total = sum(item["fact_count"] for item in results)
    cited = sum(1 for item in results if item["sources"])
    correct_source = sum(1 for item in results if item["required_source_hit"])

    print()
    print(f"Session 9 comparison complete. {len(results)} question(s), mode {mode}.")
    print(f"rag_facts_stated={rag_total}/{fact_total}")
    print(f"base_facts_stated={base_total}/{fact_total}")
    print(f"rag_answers_with_sources={cited}/{len(results)}")
    print(f"rag_answers_with_required_source={correct_source}/{len(results)}")
    print(f"dataset_sha256={dataset_hash}")
    print(f"written={OUTPUT_FILE}")


if __name__ == "__main__":
    compare()
